standard = {
        'b_sglfreqmeas': 'B_SglFreqMeas',
        'b_wbfftmon': 'B_WBFFTMon',
        'b_fscan': 'B_FScan',
        'b_pscan': 'B_PScan',
        'b_mscan': 'B_MScan',
        'b_sglfreqdf': 'B_SglFreqDF',
        'b_wbdf': 'B_WBDF',
        'b_fscandf': 'B_FScanDF',
        'b_mscandf': 'B_MScanDF',
        'b_digsglrecdecode': 'B_DigSglRecDecode',
        'b_anatvdem': 'B_AnaTVDem',
        'b_digtvdem': 'B_DigTVDem',
        'b_digbroadcastdem': 'B_DigBroadcastDem',
        'b_speccommsyssgldem': 'B_SpecCommSysSglDem',
        'b_occumeas': 'B_OccuMeas',
        'b_ifsglinte': 'B_IFSglInte',
        'b_wbsglinte': ' B_WBSglInte',
        'b_fscansglinte': 'B_FScanSglInte',
        'b_linkantedev': 'B_LinkAnteDev',
        'b_selftest': 'B_SelfTest',
        'b_queryfacidevstatus': 'B_QueryFaciDevStatus',
        'b_setdevicepower': 'B_SetDevicePower',
        'b_querydeviceinfo': 'B_QueryDeviceInfo',
        'b_stopmeas': 'B_StopMeas',
        'digsglrecdecode': 'B_DigSglRecDecode', 'anatvdem': 'B_AnaTVDem', 'digtvdem': 'B_DigTVDem',
        'digbroadcastdem': 'B_DigBroadcastDem', 'speccommsyssgldem': 'B_SpecCommSysSglDem', 'occumeas': 'B_OccuMeas',
        'ifsglinte': 'B_IFSglInte', 'wbsglinte': 'B_WBSglInte', 'fscansglinte': 'B_FScanSglInte',
        'linkantedev': 'B_LinkAnteDev', 'selftest': 'B_SelfTest', 'queryfacidevstatus': 'B_QueryFaciDevStatus',
        'setdevicepower': 'B_SetDevicePower', 'querydeviceinfo': 'B_QueryDeviceInfo', 'stopmeas': 'B_StopMeas'
}
for item in standard.items():
        print(item)
